[package]
name = "rngst-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dirs = "5.0.1"
rand = "0.8.5"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

